apiVersion: v1
kind: Secret
metadata:
  name: auto-jira-secret
  namespace: default
type: Opaque
stringData:
  JIRA_EMAIL: ""
  JIRA_API_TOKEN: ""
  GREEN_INSTANCE_ID: ""
  GREEN_API_TOKEN: ""
  GREEN_GROUP_CHAT_ID: ""
