apiVersion: v1
kind: Secret
metadata:
  name: auto-jira-secret
  namespace: default
type: Opaque
stringData:
  JIRA_EMAIL: "care-notifications@vunetsystems.com"
  JIRA_API_TOKEN: "ATATT3xFfGF0rYHGMLVYJ_njVZCCAIYstavaPw3QOe7IpGcZ_1ubrQGxlH6EQhdFC03Wnxrl8AAcoHNcg3IUeV9r1wj8aGhKoLm4yPWD_fSu_Q-6o9-J2zZX0ie_KfS7zbVcDEEwcXlNGnUoFnHzBi5wnFD3UVJjcGfl-Lw-xY8pLJgaZ-ocqZ4=931EC2F2"
  GREEN_INSTANCE_ID: "7103523858"
  GREEN_API_TOKEN: "a29efb612cb842eab150ee88ee29ca1b21086a6bce344dcea3"
  GREEN_GROUP_CHAT_ID: "120363317484205673@g.us"
